name: clipcat
description: A modern clipboard manager.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Update SDK constraint as needed

dependencies:
  flutter:
    sdk: flutter

  # Core UI & State
  cupertino_icons: ^1.0.6
  provider: ^6.1.1          # State management
  flutter_svg: ^2.0.9       # For SVG icons (like the app icon idea)

  # Clipboard & System Interaction
  super_clipboard: ^0.8.4 # Modern clipboard access (text, images, monitoring) - Needs setup!
  hotkey_manager: ^0.2.1     # Global hotkeys
  window_manager: ^0.3.7     # Control window visibility, close behavior
  system_tray: ^2.0.3        # Menu bar / System tray icon
  path_provider: ^2.1.1    # Find suitable directory for database

  # Storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # Bundled Isar core libraries
  shared_preferences: ^2.2.2 # Simple key-value settings

  # Utilities
  intl: ^0.18.1              # For date formatting
  image: ^4.1.3              # For image compression (optional)
  uuid: ^4.3.3               # For unique item IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7        # Code generation for Isar

flutter:
  uses-material-design: false # We are focusing on Cupertino
  # Add assets like icons here
  # assets:
  #   - assets/icons/